[project]
name = "clase-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "pandas>=2.3.3",
    "uvicorn>=0.37.0",
]
