CREATE TABLE IF NOT EXISTS datacrimes (
    ID TEXT PRIMARY KEY,
    CASE_NUMBER TEXT,
    DATE TIMESTAMP,
    BLOCK TEXT,
    IUCR TEXT,
    PRIMARY_TYPE TEXT,
    DESCRIPTION TEXT,
    LOCATION_DESCRIPTION TEXT,
    
    ARREST BOOLEAN,
    DOMESTIC BOOLEAN,
    BEAT INTEGER,
    DISTRICT INTEGER,
    WARD INTEGER,
    COMMUNITY_AREA INTEGER,
    FBI_CODE TEXT,
    X_COORDINATE INTEGER,
    Y_COORDINATE INTEGER,
    YEAR INTEGER,
    UPDATED_ON TIMESTAMP,
    LATITUDE FLOAT,
    LONGITUDE FLOAT
);